[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flaskr"
version = "1.0.0"
description = "A simple Flask blog app."
authors = [{name = "Fiona Githaiga", email = "fionamuthoni18@gmail.com"}]
dependencies = [
    "flask",
    "werkzeug",
    "pytest",
    "pytest-flask",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

